# Generated by Django 5.2.6 on 2025-09-30 21:11

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=app.models.upload_tutor)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('animal', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino'), ('equino', 'Equino'), ('bovino', 'Bovino'), ('ave', 'Ave')], default=None, max_length=100)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('prescricao', models.TextField(blank=True, null=True)),
                ('relato_atendimento', models.TextField(blank=True, null=True)),
                ('violento', models.BooleanField(default=False)),
                ('tipo_atendimento', models.CharField(choices=[('consulta', 'Consulta'), ('ultrasonografia', 'Ultrasonografia'), ('cirurgia', 'Cirurgia'), ('especial', 'Especial')], max_length=100)),
                ('profissional', models.CharField(choices=[('nathan', 'Nathan Esnácio'), ('yago', 'Yago Cabral'), ('matheus', 'Matheus Corrêa'), ('carlos', 'Carlos Alberto')], max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('duracao', models.IntegerField(default=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('especie', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro')], max_length=50)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=app.models.upload_paciente)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='app.cliente')),
            ],
        ),
    ]
