# Generated by Django 5.2.6 on 2025-09-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='especie',
            field=models.CharField(choices=[('', '---------'), ('canino', 'Canino'), ('felino', 'Felino'), ('equino', 'Equino'), ('bovino', 'Bovino'), ('ave', 'Ave')], default=None, max_length=100),
        ),
    ]
