# Generated by Django 5.2.6 on 2025-10-01 19:01

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agendamento_especie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.AddField(
            model_name='animal',
            name='cliente',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='app.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro')], default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_paciente),
        ),
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_paciente', to='app.animal'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_cliente', to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
