# Generated by Django 5.2.6 on 2025-10-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cliente_foto_animal_cliente_animal_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('', '---------'), ('canino', 'Canino'), ('felino', 'Felino'), ('equino', 'Equino'), ('bovino', 'Bovino'), ('ave', 'Ave')], max_length=50),
        ),
    ]
