# Generated by Django 5.2.6 on 2025-10-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_animal_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('cobertura', models.TextField(blank=True, help_text='Descreva os serviços cobertos', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_saude', to='app.animal')),
            ],
        ),
    ]
