# Generated by Django 5.2.6 on 2025-10-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_planosaude'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planos_cliente', to='app.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planosaude',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_saude', to='app.animal'),
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='cobertura',
            field=models.TextField(blank=True, null=True),
        ),
    ]
