# Generated by Django 5.2.6 on 2025-10-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_planosaude_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosaude',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_saude', to='app.animal'),
        ),
    ]
