# Generated by Django 5.2.6 on 2025-10-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_planosaude_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProcedimentoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('procedimento_descricao', models.CharField(max_length=255, verbose_name='Descrição do Procedimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='app.agendamento')),
            ],
        ),
    ]
