# Generated by Django 5.2.6 on 2025-11-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_agendamento_valor_total_animal_peso_animal_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.PositiveIntegerField(default=1)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_usados', to='app.agendamento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='app.medicamento')),
            ],
        ),
    ]
